import type { Metadata } from "next";
import { Geist, Geist_Mono, Metal, Inter } from "next/font/google";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="cursor-none">
      <body
        className={` antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
